# Generated by Django 4.1.4 on 2023-01-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=30, verbose_name='Usuario')),
                ('fecha_facturacion', models.CharField(max_length=30, verbose_name='Usuario')),
                ('fecha_vencimiento', models.CharField(max_length=30, verbose_name='Usuario')),
                ('total_pagar', models.IntegerField()),
                ('consumo', models.IntegerField()),
                ('Pagado', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='categoria',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
