# Generated by Django 4.1.4 on 2023-01-29 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=30, unique=True, verbose_name='Usuario')),
                ('fecha_facturacion', models.TimeField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.TimeField(default=django.utils.timezone.now)),
                ('total_pagar', models.IntegerField()),
                ('consumo', models.IntegerField()),
                ('Pagado', models.BooleanField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='categoria',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
