# Generated by Django 4.1.4 on 2023-01-31 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_factura_user_categoria_user_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_facturacion',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
