# Generated by Django 4.1.4 on 2023-02-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_factura_fecha_facturacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Pagado',
            field=models.CharField(default='false', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_pagar',
            field=models.IntegerField(default=200000),
        ),
    ]
