# Generated by Django 4.1.4 on 2023-01-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_factura_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.CharField(max_length=30, verbose_name='Usuario'),
        ),
    ]
